### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by yu675797450** [fossasia/visdom#803]
It's Alive!
Traceback (most recent call last):
  File "E:\Anaconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\lib\site-packages\visdom\server.py", line 1922, in <module>
    download_scripts_and_run()
  File "E:\Anaconda\lib\site-packages\visdom\server.py", line 1918, in download_scripts_and_run
    main()
  File "E:\Anaconda\lib\site-packages\visdom\server.py", line 1910, in main
    start_server(port=FLAGS.port, hostname=FLAGS.hostname, base_url=base_url,
  File "E:\Anaconda\lib\site-packages\visdom\server.py", line 1791, in start_server
    app.listen(port, max_buffer_size=1024 ** 3)
  File "E:\Anaconda\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "E:\Anaconda\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "E:\Anaconda\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "E:\Anaconda\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "E:\Anaconda\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "E:\Anaconda\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

**Comment by yu675797450** [comment]
Python 3.8.3




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jack ***@***.***&gt;; 
发送时间: 2021年5月10日(星期一) 晚上9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fossasia/visdom] NotImplementedError (#803)





 
What version of Python are you using here? Please provide more context - following the issue template.

**Comment by yu675797450** [comment]
thank you for the great tool




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jack ***@***.***&gt;; 
发送时间: 2021年5月10日(星期一) 晚上9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fossasia/visdom] NotImplementedError (#803)





 
What version of Python are you using here? Please provide more context - following the issue template.

**Comment by ambersTail** [comment]
Is this issue solved?? I run into the same error.

**Comment by JackUrb** [comment]
This seems to be a strange interaction with `tornado` and `asyncio` in Python 3.8 specifically in windows. Some documentation can be found here: https://github.com/tornadoweb/tornado/issues/2608. I'm happy to accept an implementation of this solution: https://github.com/tornadoweb/tornado/issues/2751#issuecomment-594460695 in our `server.py` to resolve this for windows.

**Comment by ambersTail** [comment]
Thanks for the reply! Problem solved!

Regards,
Amber
