### ISSUE TITLE
replay_log doesn't read the json file correctly

### ISSUE THREAD

**Issue by muhammadyaseen** [fossasia/visdom#818]
**Bug Description**
The saved .json file is not read correctly when replaying the logs.

Platform: Win 10 (with cygwin), Python 3.9, Visdom.__version__ =  0.1.8.9

**Reproduction Steps**

1. Save the environment from Browser UI.
2. Use the following code to attempt replay

```
import visdom
visdom_instance = visdom.Visdom(port=8097)
path_to_saved_log = "~/.visdom/full_lines.json"
visdom_instance.replay_log(path_to_saved_log)
```

Throws the error
```
Setting up a new session...
Traceback (most recent call last):
  File "/home/c01/pytorch_log_test/visdom_replay_test.py", line 7, in <module>
    visdom_instance.replay_log(path_to_saved_log)
  File "/home/c01/anaconda3/envs/pytorch-env/lib/python3.9/site-packages/visdom/__init__.py", line 903, in replay_log
    self._send(msg, endpoint, from_log=True)
  File "/home/c01/anaconda3/envs/pytorch-env/lib/python3.9/site-packages/visdom/__init__.py", line 691, in _send
    if msg.get('eid', None) is None:
AttributeError: 'str' object has no attribute 'get'
```

[lines_log.json.txt](https://github.com/fossasia/visdom/files/7192284/lines_log.json.txt)

**Expected behavior**

Restoring the environment / plots

**Server logs:**
The following is shown when I save the env
```
INFO:root:from web client: {"cmd":"save","data":{"window_39fb59a44ff808":{"i":"window_39fb59a44ff808","w":32.18212729627885,"h":29,"width":32.19895287958115,"height":29,"x":0,"y":0,"static":false},"window_39fb59a450a5b8":{"i":"window_39fb59a450a5b8","w":32.18212729627885,"h":29,"width":32.19895287958115,"height":29,"x":32.18212729627885,"y":0,"static":false},"window_39fb59a450f544":{"i":"window_39fb59a450f544","w":32.18212729627885,"h":29,"width":32.19895287958115,"height":29,"x":64.3642545925577,"y":0,"static":false},"window_39fb59a4513da6":{"i":"window_39fb59a4513da6","w":32.18212729627885,"h":29,"width":32.19895287958115,"height":29,"x":96.54638188883655,"y":0,"static":false},"window_39fb59a4518862":{"i":"window_39fb59a4518862","w":32.18212729627885,"h":29,"width":32.19895287958115,"height":29,"x":128.7285091851154,"y":0,"static":false},"window_39fb59a451cbae":{"i":"window_39fb59a451cbae","w":32.18212729627885,"h":29,"width":32.19895287958115,"height":29,"x":0,"y":29,"static":false},"window_39fb59a452082c":{"i":"window_39fb59a452082c","w":32.18212729627885,"h":29,"width":32.19895287958115,"height":29,"x":32.18212729627885,"y":29,"static":false},"window_39fb59a4523df6":{"i":"window_39fb59a4523df6","w":32.18212729627885,"h":29,"width":32.19895287958115,"height":29,"x":64.3642545925577,"y":29,"static":false},"window_39fb59a4527944":{"i":"window_39fb59a4527944","w":32.18212729627885,"h":29,"width":32.19895287958115,"height":29,"x":96.54638188883655,"y":29,"static":false}},"prev_eid":"full_lines","eid":"full_lines"}
```
**Additional context**
I have attached the saved log file as .txt because github won't allow json files.
In the `replay_logs` function, the line `endpoint, msg = json.loads(entry)` only returns dict keys and NOT the contents which have actual window data (position , style etc.) and the plotted data (x,y values)

**Comment by muhammadyaseen** [comment]
For convenience, here's a preview of the structure of formatted version of the saved JSON log file.

![image](https://user-images.githubusercontent.com/4466271/133932420-3d6d6136-89b4-4368-8011-58be0146434f.png)

You can see the keys `jsons` and `reload`. These string values are assigned to `endpoint, msg` when `endpoint, msg = json.loads(entry)` is executed. I'm not sure what the correct schema of the file is supposed to be.

**Comment by muhammadyaseen** [comment]
I confued saving environment with saving logs. 
You need to pass `log_to_filename` param starting a server and then use `replay_log(filename)` to restore the state.
