### ISSUE TITLE
Issue running Visdom with Windows: `pwd` is not cross-platform

### ISSUE THREAD

**Issue by fmscole** [fossasia/visdom#825]
**win10 visdom 0.1.8.9**
When I visit http://localhost:8097,follow the errors:
```
INFO:root:Application Started
You can navigate to http://localhost:8097
ERROR:tornado.application:Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8097', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\visdom\server.py", line 1635, in get
    user=getpass.getuser(),
  File "D:\ProgramData\Anaconda3\lib\getpass.py", line 168, in getuser
    import pwd
ModuleNotFoundError: No module named 'pwd'
ERROR:root:ERROR: 500: {'exc_info': (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'pwd'"), <traceback object at 0x000001AB27B03700>)}
INFO:root:Traceback: ['Traceback (most recent call last):\n', '  File "D:\\ProgramData\\Anaconda3\\lib\\site-packages\\tornado\\web.py", line 1702, in _execute\n    result = method(*self.path_args, **self.path_kwargs)\n', '  File "D:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\server.py", line 1635, in get\n    user=getpass.getuser(),\n', '  File "D:\\ProgramData\\Anaconda3\\lib\\getpass.py", line 168, in getuser\n    import pwd\n', "ModuleNotFoundError: No module named 'pwd'\n"]
ERROR:root:rendering error page
ERROR:root:[Errno 2] No such file or directory: 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\static\\error.html'
ERROR:tornado.access:500 GET / (::1) 6.00ms
```

**Comment by JackUrb** [comment]
Hi @fmscole, I don't believe we have robust windows support for visdom. The issue here is a request to find the current directory, using a Linux-specific command. I would certainly accept a PR to make it cross-platform though.

**Comment by fmscole** [comment]
@JackUrb thanks！
